language: node_js
node_js:
- 0.8
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: "cUKZZF9N/Rvu2YsmS1/ueknLXkq5ZVtYG0SQkyEOR2mOMT+6vlFqW0GXOYzfHILglvLfZCoOM4S/Vdg97yGZhU6U8U9Qt1FUeMk2Wfl7ZONNN278zxW40IeE1PMdkEXx5vHNk6+Iwk1qhXfPgNQOLBErdP8r3NI7cCICc087q9Y="
  - secure: "rGYolptM+5rGi+qehXSw4G0C5aKc+j1F+1QGnTP7zkWcPmv5rmGUhTeUaZJcF0jSBjNNZ7fU3/E8UJD2NjaC5byWCAbITwdVhSyVJLjBh09JPyMnZON8u3OyqBO2PrScS9/tnSdAGUpXLnQLvDex93X4og36qH84TvfQA2cJOb8="